use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct PresetMetadata {
    pub id: String,
    pub name: String,
    pub description: String,
    pub family: String,
    pub tags: Vec<String>,
    pub node_count: usize,
    pub connection_count: usize,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct PresetNode {
    pub id: String,
    #[serde(rename = "type")]
    pub node_type: String,
    pub name: String,
    pub x: i32,
    pub y: i32,
    pub params: Value,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct PresetConnection {
    pub id: String,
    pub from: String,
    pub to: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct FullPreset {
    pub id: String,
    pub name: String,
    pub description: String,
    pub family: String,
    pub tags: Vec<String>,
    pub nodes: Vec<PresetNode>,
    pub connections: Vec<PresetConnection>,
}

fn node(id: &str, node_type: &str, name: &str, x: i32, y: i32, params: Value) -> PresetNode {
    PresetNode {
        id: id.to_string(),
        node_type: node_type.to_string(),
        name: name.to_string(),
        x,
        y,
        params,
    }
}

fn conn(id: &str, from: &str, to: &str) -> PresetConnection {
    PresetConnection {
        id: id.to_string(),
        from: from.to_string(),
        to: to.to_string(),
    }
}

fn meta_from_full(p: &FullPreset) -> PresetMetadata {
    PresetMetadata {
        id: p.id.clone(),
        name: p.name.clone(),
        description: p.description.clone(),
        family: p.family.clone(),
        tags: p.tags.clone(),
        node_count: p.nodes.len(),
        connection_count: p.connections.len(),
    }
}

pub fn get_preset_by_id(id: &str) -> Option<FullPreset> {
    get_all_presets().into_iter().find(|p| p.id == id)
}

pub fn get_all_presets_metadata() -> Vec<PresetMetadata> {
    get_all_presets()
        .into_iter()
        .map(|p| meta_from_full(&p))
        .collect()
}

pub fn get_all_presets() -> Vec<FullPreset> {
    vec![
        // ────────────────────────────────────────────────────────────────
        // Transformer (max 3)
        // ────────────────────────────────────────────────────────────────
        FullPreset {
            id: "gpt2-small".to_string(),
            name: "GPT-2 Small".to_string(),
            description: "Decoder-only transformer (12 layers, d_model=768)".to_string(),
            family: "transformer".to_string(),
            tags: vec!["decoder".into(), "gpt2".into(), "lm".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, seq_len]"}),
                ),
                node(
                    "emb",
                    "token_embedding",
                    "Token Embedding",
                    220,
                    140,
                    serde_json::json!({"vocab_size": 50257, "d_model": 768, "padding_idx": 0, "dtype": "float32"}),
                ),
                node(
                    "pos",
                    "pos_absolute",
                    "Positional Encoding",
                    420,
                    140,
                    serde_json::json!({"d_model": 768, "max_len": 1024, "encoding_type": "learned", "dropout": 0.0}),
                ),
                node(
                    "stack",
                    "layer_stack",
                    "12x Decoder Blocks",
                    620,
                    140,
                    serde_json::json!({"num_layers": 12, "share_parameters": false}),
                ),
                node(
                    "norm",
                    "layernorm",
                    "Final LayerNorm",
                    820,
                    140,
                    serde_json::json!({"normalized_shape": 768, "eps": 1e-6, "elementwise_affine": true, "position": "pre"}),
                ),
                node(
                    "head",
                    "lm_head",
                    "LM Head",
                    1020,
                    140,
                    serde_json::json!({"d_model": 768, "vocab_size": 50257, "bias": false, "tie_weights": true}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1220,
                    140,
                    serde_json::json!({"shape": "[B, seq_len, vocab_size]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "emb"),
                conn("c2", "emb", "pos"),
                conn("c3", "pos", "stack"),
                conn("c4", "stack", "norm"),
                conn("c5", "norm", "head"),
                conn("c6", "head", "out"),
            ],
        },
        FullPreset {
            id: "llama-7b".to_string(),
            name: "LLaMA-7B".to_string(),
            description: "RoPE + RMSNorm, 32 layers, d_model=4096".to_string(),
            family: "transformer".to_string(),
            tags: vec!["decoder".into(), "llama".into(), "rope".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, seq_len]"}),
                ),
                node(
                    "emb",
                    "token_embedding",
                    "Token Embedding",
                    220,
                    140,
                    serde_json::json!({"vocab_size": 32000, "d_model": 4096, "padding_idx": 0, "dtype": "float32"}),
                ),
                node(
                    "rope",
                    "pos_rope",
                    "RoPE",
                    420,
                    140,
                    serde_json::json!({"d_model": 4096, "max_len": 4096, "base": 10000, "scaling_type": "none", "partial_rotary_factor": 1.0}),
                ),
                node(
                    "stack",
                    "layer_stack",
                    "32x Decoder Blocks",
                    620,
                    140,
                    serde_json::json!({"num_layers": 32, "share_parameters": false}),
                ),
                node(
                    "norm",
                    "rmsnorm",
                    "RMSNorm",
                    820,
                    140,
                    serde_json::json!({"normalized_shape": 4096, "eps": 1e-5, "elementwise_affine": true, "position": "pre"}),
                ),
                node(
                    "head",
                    "lm_head",
                    "LM Head",
                    1020,
                    140,
                    serde_json::json!({"d_model": 4096, "vocab_size": 32000, "bias": false, "tie_weights": true}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1220,
                    140,
                    serde_json::json!({"shape": "[B, seq_len, vocab_size]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "emb"),
                conn("c2", "emb", "rope"),
                conn("c3", "rope", "stack"),
                conn("c4", "stack", "norm"),
                conn("c5", "norm", "head"),
                conn("c6", "head", "out"),
            ],
        },
        FullPreset {
            id: "bert-base".to_string(),
            name: "BERT Base".to_string(),
            description: "Encoder-only transformer (12 layers, d_model=768)".to_string(),
            family: "transformer".to_string(),
            tags: vec!["encoder".into(), "bert".into(), "nlp".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, seq_len]"}),
                ),
                node(
                    "emb",
                    "embedding",
                    "Embedding",
                    220,
                    140,
                    serde_json::json!({"vocab_size": 30522, "d_model": 768, "padding_idx": 0, "dtype": "float32"}),
                ),
                node(
                    "pos",
                    "pos_absolute",
                    "Positional Encoding",
                    420,
                    140,
                    serde_json::json!({"d_model": 768, "max_len": 512, "encoding_type": "learned", "dropout": 0.0}),
                ),
                node(
                    "stack",
                    "layer_stack",
                    "12x Encoder Blocks",
                    620,
                    140,
                    serde_json::json!({"num_layers": 12, "share_parameters": false}),
                ),
                node(
                    "norm",
                    "layernorm",
                    "LayerNorm",
                    820,
                    140,
                    serde_json::json!({"normalized_shape": 768, "eps": 1e-6, "elementwise_affine": true, "position": "pre"}),
                ),
                node(
                    "head",
                    "classification_head",
                    "Classifier",
                    1020,
                    140,
                    serde_json::json!({"d_model": 768, "num_classes": 2, "pooling": "cls"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1220,
                    140,
                    serde_json::json!({"shape": "[B, num_classes]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "emb"),
                conn("c2", "emb", "pos"),
                conn("c3", "pos", "stack"),
                conn("c4", "stack", "norm"),
                conn("c5", "norm", "head"),
                conn("c6", "head", "out"),
            ],
        },
        // ────────────────────────────────────────────────────────────────
        // CNN (max 3)
        // ────────────────────────────────────────────────────────────────
        FullPreset {
            id: "resnet-50".to_string(),
            name: "ResNet-50".to_string(),
            description: "Residual CNN with bottleneck stages (3/4/6/3)".to_string(),
            family: "cnn".to_string(),
            tags: vec!["resnet".into(), "vision".into(), "classification".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Image Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, C, H, W]"}),
                ),
                node(
                    "stem",
                    "stem_block",
                    "Stem",
                    220,
                    140,
                    serde_json::json!({"type": "conv", "in_channels": 3, "out_channels": 64, "stride": 2, "activation": "relu"}),
                ),
                node(
                    "s1",
                    "stage_block",
                    "Stage 1",
                    420,
                    140,
                    serde_json::json!({"num_blocks": 3, "block_type": "bottleneck", "in_channels": 64, "out_channels": 256, "stride": 1}),
                ),
                node(
                    "s2",
                    "stage_block",
                    "Stage 2",
                    620,
                    140,
                    serde_json::json!({"num_blocks": 4, "block_type": "bottleneck", "in_channels": 256, "out_channels": 512, "stride": 2}),
                ),
                node(
                    "s3",
                    "stage_block",
                    "Stage 3",
                    820,
                    140,
                    serde_json::json!({"num_blocks": 6, "block_type": "bottleneck", "in_channels": 512, "out_channels": 1024, "stride": 2}),
                ),
                node(
                    "s4",
                    "stage_block",
                    "Stage 4",
                    1020,
                    140,
                    serde_json::json!({"num_blocks": 3, "block_type": "bottleneck", "in_channels": 1024, "out_channels": 2048, "stride": 2}),
                ),
                node(
                    "pool",
                    "global_pool",
                    "Global AvgPool",
                    1220,
                    140,
                    serde_json::json!({"type": "avg"}),
                ),
                node(
                    "head",
                    "classification_head",
                    "Classifier",
                    1420,
                    140,
                    serde_json::json!({"d_model": 2048, "num_classes": 1000, "pooling": "avg"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1620,
                    140,
                    serde_json::json!({"shape": "[B, num_classes]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "stem"),
                conn("c2", "stem", "s1"),
                conn("c3", "s1", "s2"),
                conn("c4", "s2", "s3"),
                conn("c5", "s3", "s4"),
                conn("c6", "s4", "pool"),
                conn("c7", "pool", "head"),
                conn("c8", "head", "out"),
            ],
        },
        FullPreset {
            id: "convnext-tiny".to_string(),
            name: "ConvNeXt-Tiny".to_string(),
            description: "Modernized ConvNet with ConvNeXt blocks".to_string(),
            family: "cnn".to_string(),
            tags: vec!["convnext".into(), "vision".into(), "classification".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Image Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, C, H, W]"}),
                ),
                node(
                    "stem",
                    "stem_block",
                    "Stem",
                    220,
                    140,
                    serde_json::json!({"type": "conv", "in_channels": 3, "out_channels": 96, "stride": 4, "activation": "gelu"}),
                ),
                node(
                    "s1",
                    "stage_block",
                    "Stage 1",
                    420,
                    140,
                    serde_json::json!({"num_blocks": 3, "block_type": "convnext", "in_channels": 96, "out_channels": 96, "stride": 1}),
                ),
                node(
                    "s2",
                    "stage_block",
                    "Stage 2",
                    620,
                    140,
                    serde_json::json!({"num_blocks": 3, "block_type": "convnext", "in_channels": 96, "out_channels": 192, "stride": 2}),
                ),
                node(
                    "s3",
                    "stage_block",
                    "Stage 3",
                    820,
                    140,
                    serde_json::json!({"num_blocks": 9, "block_type": "convnext", "in_channels": 192, "out_channels": 384, "stride": 2}),
                ),
                node(
                    "s4",
                    "stage_block",
                    "Stage 4",
                    1020,
                    140,
                    serde_json::json!({"num_blocks": 3, "block_type": "convnext", "in_channels": 384, "out_channels": 768, "stride": 2}),
                ),
                node(
                    "pool",
                    "global_pool",
                    "Global AvgPool",
                    1220,
                    140,
                    serde_json::json!({"type": "avg"}),
                ),
                node(
                    "head",
                    "classification_head",
                    "Classifier",
                    1420,
                    140,
                    serde_json::json!({"d_model": 768, "num_classes": 1000, "pooling": "avg"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1620,
                    140,
                    serde_json::json!({"shape": "[B, num_classes]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "stem"),
                conn("c2", "stem", "s1"),
                conn("c3", "s1", "s2"),
                conn("c4", "s2", "s3"),
                conn("c5", "s3", "s4"),
                conn("c6", "s4", "pool"),
                conn("c7", "pool", "head"),
                conn("c8", "head", "out"),
            ],
        },
        FullPreset {
            id: "efficientnet-b0".to_string(),
            name: "EfficientNet-B0".to_string(),
            description: "MBConv stages with progressive scaling".to_string(),
            family: "cnn".to_string(),
            tags: vec!["efficientnet".into(), "mbconv".into(), "vision".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Image Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, C, H, W]"}),
                ),
                node(
                    "stem",
                    "stem_block",
                    "Stem",
                    220,
                    140,
                    serde_json::json!({"type": "conv", "in_channels": 3, "out_channels": 32, "stride": 2, "activation": "silu"}),
                ),
                node(
                    "s1",
                    "stage_block",
                    "Stage 1",
                    420,
                    140,
                    serde_json::json!({"num_blocks": 1, "block_type": "mbconv", "in_channels": 32, "out_channels": 16, "stride": 1}),
                ),
                node(
                    "s2",
                    "stage_block",
                    "Stage 2",
                    620,
                    140,
                    serde_json::json!({"num_blocks": 2, "block_type": "mbconv", "in_channels": 16, "out_channels": 24, "stride": 2}),
                ),
                node(
                    "s3",
                    "stage_block",
                    "Stage 3",
                    820,
                    140,
                    serde_json::json!({"num_blocks": 2, "block_type": "mbconv", "in_channels": 24, "out_channels": 40, "stride": 2}),
                ),
                node(
                    "s4",
                    "stage_block",
                    "Stage 4",
                    1020,
                    140,
                    serde_json::json!({"num_blocks": 3, "block_type": "mbconv", "in_channels": 40, "out_channels": 80, "stride": 2}),
                ),
                node(
                    "s5",
                    "stage_block",
                    "Stage 5",
                    1220,
                    140,
                    serde_json::json!({"num_blocks": 3, "block_type": "mbconv", "in_channels": 80, "out_channels": 112, "stride": 1}),
                ),
                node(
                    "s6",
                    "stage_block",
                    "Stage 6",
                    1420,
                    140,
                    serde_json::json!({"num_blocks": 4, "block_type": "mbconv", "in_channels": 112, "out_channels": 192, "stride": 2}),
                ),
                node(
                    "s7",
                    "stage_block",
                    "Stage 7",
                    1620,
                    140,
                    serde_json::json!({"num_blocks": 1, "block_type": "mbconv", "in_channels": 192, "out_channels": 320, "stride": 1}),
                ),
                node(
                    "pool",
                    "global_pool",
                    "Global AvgPool",
                    1820,
                    140,
                    serde_json::json!({"type": "avg"}),
                ),
                node(
                    "head",
                    "classification_head",
                    "Classifier",
                    2020,
                    140,
                    serde_json::json!({"d_model": 320, "num_classes": 1000, "pooling": "avg"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    2220,
                    140,
                    serde_json::json!({"shape": "[B, num_classes]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "stem"),
                conn("c2", "stem", "s1"),
                conn("c3", "s1", "s2"),
                conn("c4", "s2", "s3"),
                conn("c5", "s3", "s4"),
                conn("c6", "s4", "s5"),
                conn("c7", "s5", "s6"),
                conn("c8", "s6", "s7"),
                conn("c9", "s7", "pool"),
                conn("c10", "pool", "head"),
                conn("c11", "head", "out"),
            ],
        },
        // ────────────────────────────────────────────────────────────────
        // MoE (max 3)
        // ────────────────────────────────────────────────────────────────
        FullPreset {
            id: "mixtral-8x7b".to_string(),
            name: "Mixtral-8x7B".to_string(),
            description: "MoE decoder block with routed experts".to_string(),
            family: "moe".to_string(),
            tags: vec!["moe".into(), "mixtral".into(), "decoder".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, seq_len]"}),
                ),
                node(
                    "emb",
                    "token_embedding",
                    "Token Embedding",
                    220,
                    140,
                    serde_json::json!({"vocab_size": 32000, "d_model": 4096, "padding_idx": 0, "dtype": "float32"}),
                ),
                node(
                    "rope",
                    "pos_rope",
                    "RoPE",
                    420,
                    140,
                    serde_json::json!({"d_model": 4096, "max_len": 32768, "base": 10000, "scaling_type": "none", "partial_rotary_factor": 1.0}),
                ),
                node(
                    "moe",
                    "moe_block",
                    "MoE Block",
                    620,
                    140,
                    serde_json::json!({"num_experts": 8, "top_k": 2, "d_model": 4096, "expert_d_ff": 14336, "expert_type": "gated_ffn", "router_type": "top_k", "router_bias": false, "capacity_factor": 1.25, "aux_loss_coef": 0.01, "shared_experts": 0}),
                ),
                node(
                    "norm",
                    "rmsnorm",
                    "RMSNorm",
                    820,
                    140,
                    serde_json::json!({"normalized_shape": 4096, "eps": 1e-5, "elementwise_affine": true, "position": "pre"}),
                ),
                node(
                    "head",
                    "lm_head",
                    "LM Head",
                    1020,
                    140,
                    serde_json::json!({"d_model": 4096, "vocab_size": 32000, "bias": false, "tie_weights": true}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1220,
                    140,
                    serde_json::json!({"shape": "[B, seq_len, vocab_size]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "emb"),
                conn("c2", "emb", "rope"),
                conn("c3", "rope", "moe"),
                conn("c4", "moe", "norm"),
                conn("c5", "norm", "head"),
                conn("c6", "head", "out"),
            ],
        },
        FullPreset {
            id: "switch-transformer".to_string(),
            name: "Switch Transformer".to_string(),
            description: "Sparse MoE encoder with top-1 routing".to_string(),
            family: "moe".to_string(),
            tags: vec!["moe".into(), "encoder".into(), "switch".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, seq_len]"}),
                ),
                node(
                    "emb",
                    "embedding",
                    "Embedding",
                    220,
                    140,
                    serde_json::json!({"vocab_size": 32128, "d_model": 768, "padding_idx": 0, "dtype": "float32"}),
                ),
                node(
                    "moe",
                    "moe_layer",
                    "MoE Layer",
                    420,
                    140,
                    serde_json::json!({"num_experts": 64, "top_k": 1, "d_model": 768, "expert_d_ff": 3072, "expert_type": "ffn", "router_type": "softmax", "shared_experts": 0, "aux_loss_coef": 0.01, "z_loss_coef": 0.0001, "capacity_factor": 1.25, "dropout": 0.0}),
                ),
                node(
                    "norm",
                    "layernorm",
                    "LayerNorm",
                    620,
                    140,
                    serde_json::json!({"normalized_shape": 768, "eps": 1e-6, "elementwise_affine": true, "position": "pre"}),
                ),
                node(
                    "head",
                    "classification_head",
                    "Classifier",
                    820,
                    140,
                    serde_json::json!({"d_model": 768, "num_classes": 10, "pooling": "cls"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1020,
                    140,
                    serde_json::json!({"shape": "[B, num_classes]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "emb"),
                conn("c2", "emb", "moe"),
                conn("c3", "moe", "norm"),
                conn("c4", "norm", "head"),
                conn("c5", "head", "out"),
            ],
        },
        FullPreset {
            id: "deepseek-moe".to_string(),
            name: "DeepSeek-MoE".to_string(),
            description: "Fine-grained MoE with shared + routed experts (d_model=2048)".to_string(),
            family: "moe".to_string(),
            tags: vec![
                "moe".into(),
                "deepseek".into(),
                "shared-expert".into(),
                "decoder".into(),
            ],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, seq_len]"}),
                ),
                node(
                    "emb",
                    "token_embedding",
                    "Token Embedding",
                    220,
                    140,
                    serde_json::json!({"vocab_size": 102400, "d_model": 2048, "padding_idx": 0, "dtype": "float32"}),
                ),
                node(
                    "rope",
                    "pos_rope",
                    "RoPE",
                    420,
                    140,
                    serde_json::json!({"d_model": 2048, "max_len": 4096, "base": 10000, "scaling_type": "none", "partial_rotary_factor": 1.0}),
                ),
                node(
                    "moe",
                    "moe_block",
                    "Fine-Grained MoE",
                    620,
                    140,
                    serde_json::json!({"num_experts": 64, "top_k": 6, "d_model": 2048, "expert_d_ff": 1408, "expert_type": "gated_ffn", "router_type": "top_k", "router_bias": false, "capacity_factor": 1.0, "aux_loss_coef": 0.001, "shared_experts": 2}),
                ),
                node(
                    "norm",
                    "rmsnorm",
                    "RMSNorm",
                    820,
                    140,
                    serde_json::json!({"normalized_shape": 2048, "eps": 1e-6, "elementwise_affine": true, "position": "pre"}),
                ),
                node(
                    "head",
                    "lm_head",
                    "LM Head",
                    1020,
                    140,
                    serde_json::json!({"d_model": 2048, "vocab_size": 102400, "bias": false, "tie_weights": false}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1220,
                    140,
                    serde_json::json!({"shape": "[B, seq_len, vocab_size]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "emb"),
                conn("c2", "emb", "rope"),
                conn("c3", "rope", "moe"),
                conn("c4", "moe", "norm"),
                conn("c5", "norm", "head"),
                conn("c6", "head", "out"),
            ],
        },
        // ────────────────────────────────────────────────────────────────
        // SSM (max 3)
        // ────────────────────────────────────────────────────────────────
        FullPreset {
            id: "mamba-s6".to_string(),
            name: "Mamba (S6)".to_string(),
            description: "Selective SSM block for long sequences".to_string(),
            family: "ssm".to_string(),
            tags: vec!["mamba".into(), "ssm".into(), "sequence".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, seq_len]"}),
                ),
                node(
                    "emb",
                    "token_embedding",
                    "Token Embedding",
                    220,
                    140,
                    serde_json::json!({"vocab_size": 32000, "d_model": 768, "padding_idx": 0}),
                ),
                node(
                    "s6",
                    "s6_block",
                    "S6 Block",
                    420,
                    140,
                    serde_json::json!({"d_model": 768, "d_state": 16, "expand": 2, "dt_rank": 48, "conv_kernel": 4, "bias": false}),
                ),
                node(
                    "norm",
                    "rmsnorm",
                    "RMSNorm",
                    620,
                    140,
                    serde_json::json!({"normalized_shape": 768, "eps": 1e-5, "elementwise_affine": true}),
                ),
                node(
                    "head",
                    "lm_head",
                    "LM Head",
                    820,
                    140,
                    serde_json::json!({"d_model": 768, "vocab_size": 32000, "bias": false, "tie_weights": true}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1020,
                    140,
                    serde_json::json!({"shape": "[B, seq_len, vocab_size]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "emb"),
                conn("c2", "emb", "s6"),
                conn("c3", "s6", "norm"),
                conn("c4", "norm", "head"),
                conn("c5", "head", "out"),
            ],
        },
        FullPreset {
            id: "s4".to_string(),
            name: "S4".to_string(),
            description: "Structured State Space with HiPPO init".to_string(),
            family: "ssm".to_string(),
            tags: vec!["s4".into(), "ssm".into(), "hippo".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, seq_len]"}),
                ),
                node(
                    "emb",
                    "token_embedding",
                    "Token Embedding",
                    220,
                    140,
                    serde_json::json!({"vocab_size": 32000, "d_model": 512, "padding_idx": 0}),
                ),
                node(
                    "s4",
                    "s4_block",
                    "S4 Block",
                    420,
                    140,
                    serde_json::json!({"d_model": 512, "d_state": 64, "ssm_type": "s4d", "init_method": "hippo", "normalization": "layer_norm"}),
                ),
                node(
                    "norm",
                    "layernorm",
                    "LayerNorm",
                    620,
                    140,
                    serde_json::json!({"normalized_shape": 512, "eps": 1e-6, "elementwise_affine": true}),
                ),
                node(
                    "head",
                    "lm_head",
                    "LM Head",
                    820,
                    140,
                    serde_json::json!({"d_model": 512, "vocab_size": 32000, "bias": false, "tie_weights": true}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1020,
                    140,
                    serde_json::json!({"shape": "[B, seq_len, vocab_size]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "emb"),
                conn("c2", "emb", "s4"),
                conn("c3", "s4", "norm"),
                conn("c4", "norm", "head"),
                conn("c5", "head", "out"),
            ],
        },
        FullPreset {
            id: "jamba".to_string(),
            name: "Jamba".to_string(),
            description: "Hybrid Mamba + Transformer decoder (d_model=4096, 32 layers)".to_string(),
            family: "ssm".to_string(),
            tags: vec![
                "jamba".into(),
                "hybrid".into(),
                "mamba".into(),
                "transformer".into(),
            ],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, seq_len]"}),
                ),
                node(
                    "emb",
                    "token_embedding",
                    "Token Embedding",
                    220,
                    140,
                    serde_json::json!({"vocab_size": 65536, "d_model": 4096, "padding_idx": 0, "dtype": "float32"}),
                ),
                node(
                    "rope",
                    "pos_rope",
                    "RoPE",
                    420,
                    140,
                    serde_json::json!({"d_model": 4096, "max_len": 256000, "base": 10000, "scaling_type": "none", "partial_rotary_factor": 1.0}),
                ),
                node(
                    "ssm",
                    "s6_block",
                    "Mamba Block",
                    620,
                    140,
                    serde_json::json!({"d_model": 4096, "d_state": 16, "expand": 2, "dt_rank": 256, "conv_kernel": 4, "bias": false}),
                ),
                node(
                    "attn",
                    "mha_attention",
                    "Self-Attention",
                    820,
                    140,
                    serde_json::json!({"n_heads": 32, "head_dim": 128, "d_model": 4096, "dropout": 0.0, "bias": false, "causal": true}),
                ),
                node(
                    "norm",
                    "rmsnorm",
                    "RMSNorm",
                    1020,
                    140,
                    serde_json::json!({"normalized_shape": 4096, "eps": 1e-5, "elementwise_affine": true, "position": "pre"}),
                ),
                node(
                    "head",
                    "lm_head",
                    "LM Head",
                    1220,
                    140,
                    serde_json::json!({"d_model": 4096, "vocab_size": 65536, "bias": false, "tie_weights": false}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1420,
                    140,
                    serde_json::json!({"shape": "[B, seq_len, vocab_size]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "emb"),
                conn("c2", "emb", "rope"),
                conn("c3", "rope", "ssm"),
                conn("c4", "ssm", "attn"),
                conn("c5", "attn", "norm"),
                conn("c6", "norm", "head"),
                conn("c7", "head", "out"),
            ],
        },
        // ────────────────────────────────────────────────────────────────
        // Diffusion (max 3)
        // ────────────────────────────────────────────────────────────────
        FullPreset {
            id: "ddpm-unet".to_string(),
            name: "DDPM U-Net".to_string(),
            description: "U-Net denoiser with timestep conditioning".to_string(),
            family: "diffusion".to_string(),
            tags: vec!["diffusion".into(), "unet".into(), "ddpm".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Noisy Latent",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, C, H, W]"}),
                ),
                node(
                    "noise",
                    "noise_scheduler",
                    "Noise Scheduler",
                    220,
                    140,
                    serde_json::json!({"num_train_timesteps": 1000, "beta_start": 0.0001, "beta_end": 0.02, "beta_schedule": "scaled_linear"}),
                ),
                node(
                    "time",
                    "timestep_embedding",
                    "Timestep Embedding",
                    420,
                    140,
                    serde_json::json!({"channels": 320, "time_embed_dim": 1280, "act_fn": "silu"}),
                ),
                node(
                    "unet",
                    "unet_block",
                    "U-Net Block",
                    620,
                    140,
                    serde_json::json!({"in_channels": 64, "out_channels": 128, "skip_channels": 64, "activation": "silu"}),
                ),
                node(
                    "res",
                    "residual_block",
                    "Residual Block",
                    820,
                    140,
                    serde_json::json!({"in_channels": 256, "out_channels": 256, "d_time_emb": 1280, "dropout": 0.0, "activation": "silu"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1020,
                    140,
                    serde_json::json!({"shape": "[B, C, H, W]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "noise"),
                conn("c2", "noise", "time"),
                conn("c3", "time", "unet"),
                conn("c4", "unet", "res"),
                conn("c5", "res", "out"),
            ],
        },
        FullPreset {
            id: "dit-base".to_string(),
            name: "DiT Base".to_string(),
            description: "Diffusion Transformer (patchify → DiT → depatchify)".to_string(),
            family: "diffusion".to_string(),
            tags: vec!["diffusion".into(), "transformer".into(), "dit".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Latent Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, C, H, W]"}),
                ),
                node(
                    "patch",
                    "patchify",
                    "Patchify",
                    220,
                    140,
                    serde_json::json!({"patch_size": 2, "in_channels": 4, "embed_dim": 1152}),
                ),
                node(
                    "dit",
                    "dit_block",
                    "DiT Block",
                    420,
                    140,
                    serde_json::json!({"input_size": 32, "patch_size": 2, "in_channels": 4, "embed_dim": 1152, "depth": 28, "num_heads": 16, "mlp_ratio": 4.0, "learn_sigma": true}),
                ),
                node(
                    "depatch",
                    "depatchify",
                    "Depatchify",
                    620,
                    140,
                    serde_json::json!({"patch_size": 2, "out_channels": 8}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    820,
                    140,
                    serde_json::json!({"shape": "[B, C, H, W]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "patch"),
                conn("c2", "patch", "dit"),
                conn("c3", "dit", "depatch"),
                conn("c4", "depatch", "out"),
            ],
        },
        FullPreset {
            id: "sd-ldm".to_string(),
            name: "Stable Diffusion LDM".to_string(),
            description: "Latent diffusion: VAE encoder → U-Net denoiser → VAE decoder".to_string(),
            family: "diffusion".to_string(),
            tags: vec![
                "stable-diffusion".into(),
                "ldm".into(),
                "latent".into(),
                "vae".into(),
            ],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Image Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, 3, 512, 512]"}),
                ),
                node(
                    "vae_enc",
                    "vae_encoder",
                    "VAE Encoder",
                    220,
                    140,
                    serde_json::json!({"in_channels": 3, "latent_channels": 4, "base_channels": 128, "ch_mult": [1,2,4,4], "num_res_blocks": 2, "dropout": 0.0}),
                ),
                node(
                    "noise",
                    "noise_scheduler",
                    "DDPM Scheduler",
                    420,
                    140,
                    serde_json::json!({"num_train_timesteps": 1000, "beta_start": 0.00085, "beta_end": 0.012, "beta_schedule": "scaled_linear"}),
                ),
                node(
                    "time",
                    "timestep_embedding",
                    "Timestep Embed",
                    620,
                    140,
                    serde_json::json!({"channels": 320, "time_embed_dim": 1280, "act_fn": "silu"}),
                ),
                node(
                    "unet",
                    "unet_block",
                    "U-Net Denoiser",
                    820,
                    140,
                    serde_json::json!({"in_channels": 4, "out_channels": 4, "skip_channels": 256, "activation": "silu"}),
                ),
                node(
                    "vae_dec",
                    "vae_decoder",
                    "VAE Decoder",
                    1020,
                    140,
                    serde_json::json!({"latent_channels": 4, "out_channels": 3, "base_channels": 128, "ch_mult": [1,2,4,4], "num_res_blocks": 2}),
                ),
                node(
                    "out",
                    "output",
                    "Output Image",
                    1220,
                    140,
                    serde_json::json!({"shape": "[B, 3, 512, 512]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "vae_enc"),
                conn("c2", "vae_enc", "noise"),
                conn("c3", "noise", "time"),
                conn("c4", "time", "unet"),
                conn("c5", "unet", "vae_dec"),
                conn("c6", "vae_dec", "out"),
            ],
        },
        // ────────────────────────────────────────────────────────────────
        // GNN (max 3)
        // ────────────────────────────────────────────────────────────────
        FullPreset {
            id: "gcn".to_string(),
            name: "GCN".to_string(),
            description: "Graph Convolutional Network (Kipf & Welling)".to_string(),
            family: "gnn".to_string(),
            tags: vec!["gcn".into(), "graph".into(), "classification".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Graph Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[N, F]"}),
                ),
                node(
                    "gcn",
                    "gcn_conv",
                    "GCN Conv",
                    220,
                    140,
                    serde_json::json!({"in_channels": 16, "out_channels": 64, "improved": false, "cached": false, "add_self_loops": true, "normalize": true, "bias": true}),
                ),
                node(
                    "norm",
                    "graph_norm",
                    "GraphNorm",
                    420,
                    140,
                    serde_json::json!({"in_channels": 64, "eps": 1e-5}),
                ),
                node(
                    "pool",
                    "global_mean_pool",
                    "Global Mean Pool",
                    620,
                    140,
                    serde_json::json!({}),
                ),
                node(
                    "head",
                    "classification_head",
                    "Classifier",
                    820,
                    140,
                    serde_json::json!({"d_model": 64, "num_classes": 10, "pooling": "mean"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1020,
                    140,
                    serde_json::json!({"shape": "[B, num_classes]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "gcn"),
                conn("c2", "gcn", "norm"),
                conn("c3", "norm", "pool"),
                conn("c4", "pool", "head"),
                conn("c5", "head", "out"),
            ],
        },
        FullPreset {
            id: "gat".to_string(),
            name: "GAT".to_string(),
            description: "Graph Attention Network".to_string(),
            family: "gnn".to_string(),
            tags: vec!["gat".into(), "attention".into(), "graph".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Graph Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[N, F]"}),
                ),
                node(
                    "gat",
                    "gat_conv",
                    "GAT Conv",
                    220,
                    140,
                    serde_json::json!({"in_channels": 16, "out_channels": 8, "heads": 8, "concat": true, "negative_slope": 0.2, "dropout": 0.6, "add_self_loops": true, "bias": true}),
                ),
                node(
                    "norm",
                    "graph_norm",
                    "GraphNorm",
                    420,
                    140,
                    serde_json::json!({"in_channels": 64, "eps": 1e-5}),
                ),
                node(
                    "pool",
                    "global_mean_pool",
                    "Global Mean Pool",
                    620,
                    140,
                    serde_json::json!({}),
                ),
                node(
                    "head",
                    "classification_head",
                    "Classifier",
                    820,
                    140,
                    serde_json::json!({"d_model": 64, "num_classes": 10, "pooling": "mean"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1020,
                    140,
                    serde_json::json!({"shape": "[B, num_classes]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "gat"),
                conn("c2", "gat", "norm"),
                conn("c3", "norm", "pool"),
                conn("c4", "pool", "head"),
                conn("c5", "head", "out"),
            ],
        },
        FullPreset {
            id: "graphsage".to_string(),
            name: "GraphSAGE".to_string(),
            description: "Inductive graph learning with SAGE conv (mean aggregation)".to_string(),
            family: "gnn".to_string(),
            tags: vec!["sage".into(), "inductive".into(), "graph".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Graph Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[N, F]"}),
                ),
                node(
                    "sage1",
                    "sage_conv",
                    "SAGE Conv 1",
                    220,
                    140,
                    serde_json::json!({"in_channels": 16, "out_channels": 64, "normalize": true, "concat": false, "root_weight": true, "bias": true}),
                ),
                node(
                    "norm1",
                    "graph_norm",
                    "GraphNorm",
                    420,
                    140,
                    serde_json::json!({"in_channels": 64, "eps": 1e-5}),
                ),
                node(
                    "drop",
                    "dropout",
                    "Dropout",
                    620,
                    140,
                    serde_json::json!({"rate": 0.5}),
                ),
                node(
                    "sage2",
                    "sage_conv",
                    "SAGE Conv 2",
                    820,
                    140,
                    serde_json::json!({"in_channels": 64, "out_channels": 64, "normalize": true, "concat": false, "root_weight": true, "bias": true}),
                ),
                node(
                    "pool",
                    "global_mean_pool",
                    "Global Mean Pool",
                    1020,
                    140,
                    serde_json::json!({}),
                ),
                node(
                    "head",
                    "classification_head",
                    "Classifier",
                    1220,
                    140,
                    serde_json::json!({"d_model": 64, "num_classes": 10, "pooling": "mean"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1420,
                    140,
                    serde_json::json!({"shape": "[B, num_classes]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "sage1"),
                conn("c2", "sage1", "norm1"),
                conn("c3", "norm1", "drop"),
                conn("c4", "drop", "sage2"),
                conn("c5", "sage2", "pool"),
                conn("c6", "pool", "head"),
                conn("c7", "head", "out"),
            ],
        },
        // ────────────────────────────────────────────────────────────────
        // GAN (max 3)
        // ────────────────────────────────────────────────────────────────
        FullPreset {
            id: "dcgan-generator".to_string(),
            name: "DCGAN Generator".to_string(),
            description: "Transposed conv upsampling blocks".to_string(),
            family: "gan".to_string(),
            tags: vec!["gan".into(), "dcgan".into(), "generator".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Latent Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, z_dim]"}),
                ),
                node(
                    "z",
                    "gan_noise_z",
                    "Noise z",
                    220,
                    140,
                    serde_json::json!({"dim": 100, "distribution": "gaussian"}),
                ),
                node(
                    "g1",
                    "dcgan_generator_block",
                    "Gen Block",
                    420,
                    140,
                    serde_json::json!({"out_channels": 256, "kernel": 4, "stride": 2, "padding": 1, "activation": "relu"}),
                ),
                node(
                    "g2",
                    "dcgan_generator_block",
                    "Gen Block",
                    620,
                    140,
                    serde_json::json!({"out_channels": 128, "kernel": 4, "stride": 2, "padding": 1, "activation": "relu"}),
                ),
                node(
                    "out",
                    "output",
                    "Output Image",
                    820,
                    140,
                    serde_json::json!({"shape": "[B, C, H, W]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "z"),
                conn("c2", "z", "g1"),
                conn("c3", "g1", "g2"),
                conn("c4", "g2", "out"),
            ],
        },
        FullPreset {
            id: "stylegan2".to_string(),
            name: "StyleGAN2 Synthesis".to_string(),
            description: "StyleGAN2 synthesis stages".to_string(),
            family: "gan".to_string(),
            tags: vec!["gan".into(), "stylegan".into(), "synthesis".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Style Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, w_dim]"}),
                ),
                node(
                    "s1",
                    "stylegan_synthesis_block",
                    "Synthesis 256",
                    220,
                    140,
                    serde_json::json!({"resolution": 256, "channels": 512}),
                ),
                node(
                    "s2",
                    "stylegan_synthesis_block",
                    "Synthesis 1024",
                    420,
                    140,
                    serde_json::json!({"resolution": 1024, "channels": 256}),
                ),
                node(
                    "out",
                    "output",
                    "Output Image",
                    620,
                    140,
                    serde_json::json!({"shape": "[B, C, H, W]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "s1"),
                conn("c2", "s1", "s2"),
                conn("c3", "s2", "out"),
            ],
        },
        FullPreset {
            id: "dcgan-discriminator".to_string(),
            name: "DCGAN Discriminator".to_string(),
            description: "Strided conv downsampling → real/fake verdict".to_string(),
            family: "gan".to_string(),
            tags: vec!["gan".into(), "dcgan".into(), "discriminator".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Image Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, C, H, W]"}),
                ),
                node(
                    "d1",
                    "dcgan_discriminator_block",
                    "Disc Block 1",
                    220,
                    140,
                    serde_json::json!({"out_channels": 64, "kernel": 4, "stride": 2, "padding": 1, "activation": "leaky_relu"}),
                ),
                node(
                    "d2",
                    "dcgan_discriminator_block",
                    "Disc Block 2",
                    420,
                    140,
                    serde_json::json!({"out_channels": 128, "kernel": 4, "stride": 2, "padding": 1, "activation": "leaky_relu"}),
                ),
                node(
                    "d3",
                    "dcgan_discriminator_block",
                    "Disc Block 3",
                    620,
                    140,
                    serde_json::json!({"out_channels": 256, "kernel": 4, "stride": 2, "padding": 1, "activation": "leaky_relu"}),
                ),
                node(
                    "flatten",
                    "flatten",
                    "Flatten",
                    820,
                    140,
                    serde_json::json!({"start_dim": 1}),
                ),
                node(
                    "proj",
                    "linear_projection",
                    "Verdict Head",
                    1020,
                    140,
                    serde_json::json!({"in_features": 4096, "out_features": 1, "bias": true, "activation": "none"}),
                ),
                node(
                    "out",
                    "output",
                    "Real/Fake Score",
                    1220,
                    140,
                    serde_json::json!({"shape": "[B, 1]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "d1"),
                conn("c2", "d1", "d2"),
                conn("c3", "d2", "d3"),
                conn("c4", "d3", "flatten"),
                conn("c5", "flatten", "proj"),
                conn("c6", "proj", "out"),
            ],
        },
        // ────────────────────────────────────────────────────────────────
        // RNN (max 3)
        // ────────────────────────────────────────────────────────────────
        FullPreset {
            id: "lstm".to_string(),
            name: "LSTM".to_string(),
            description: "Stacked LSTM for sequence modeling".to_string(),
            family: "rnn".to_string(),
            tags: vec!["rnn".into(), "lstm".into(), "sequence".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Sequence Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, T, F]"}),
                ),
                node(
                    "lstm",
                    "lstm",
                    "LSTM",
                    220,
                    140,
                    serde_json::json!({"input_size": 256, "hidden_size": 512, "num_layers": 2, "batch_first": true, "dropout": 0.1}),
                ),
                node(
                    "proj",
                    "linear_projection",
                    "Projection",
                    420,
                    140,
                    serde_json::json!({"in_features": 512, "out_features": 10, "bias": true, "activation": "none"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    620,
                    140,
                    serde_json::json!({"shape": "[B, T, output_dim]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "lstm"),
                conn("c2", "lstm", "proj"),
                conn("c3", "proj", "out"),
            ],
        },
        FullPreset {
            id: "gru".to_string(),
            name: "GRU".to_string(),
            description: "Stacked GRU for sequence modeling".to_string(),
            family: "rnn".to_string(),
            tags: vec!["rnn".into(), "gru".into(), "sequence".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Sequence Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, T, F]"}),
                ),
                node(
                    "gru",
                    "gru",
                    "GRU",
                    220,
                    140,
                    serde_json::json!({"input_size": 256, "hidden_size": 512, "num_layers": 2, "batch_first": true, "dropout": 0.1}),
                ),
                node(
                    "proj",
                    "linear_projection",
                    "Projection",
                    420,
                    140,
                    serde_json::json!({"in_features": 512, "out_features": 10, "bias": true, "activation": "none"}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    620,
                    140,
                    serde_json::json!({"shape": "[B, T, output_dim]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "gru"),
                conn("c2", "gru", "proj"),
                conn("c3", "proj", "out"),
            ],
        },
        FullPreset {
            id: "bilstm-seq2seq".to_string(),
            name: "BiLSTM Seq2Seq".to_string(),
            description: "Bidirectional LSTM encoder → LSTM decoder with Bahdanau attention"
                .to_string(),
            family: "rnn".to_string(),
            tags: vec![
                "rnn".into(),
                "bilstm".into(),
                "seq2seq".into(),
                "attention".into(),
            ],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Source Sequence",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, T_src, F]"}),
                ),
                node(
                    "enc",
                    "bilstm",
                    "BiLSTM Encoder",
                    220,
                    140,
                    serde_json::json!({"input_size": 256, "hidden_size": 512, "num_layers": 2, "batch_first": true, "dropout": 0.1, "bidirectional": true}),
                ),
                node(
                    "attn",
                    "seq2seq_attention",
                    "Bahdanau Attention",
                    420,
                    140,
                    serde_json::json!({"attentionType": "bahdanau"}),
                ),
                node(
                    "dec",
                    "lstm",
                    "LSTM Decoder",
                    620,
                    140,
                    serde_json::json!({"input_size": 512, "hidden_size": 512, "num_layers": 1, "batch_first": true, "dropout": 0.0}),
                ),
                node(
                    "proj",
                    "linear_projection",
                    "Output Projection",
                    820,
                    140,
                    serde_json::json!({"in_features": 512, "out_features": 32000, "bias": true, "activation": "none"}),
                ),
                node(
                    "out",
                    "output",
                    "Target Tokens",
                    1020,
                    140,
                    serde_json::json!({"shape": "[B, T_tgt, vocab_size]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "enc"),
                conn("c2", "enc", "attn"),
                conn("c3", "attn", "dec"),
                conn("c4", "dec", "proj"),
                conn("c5", "proj", "out"),
            ],
        },
        // ────────────────────────────────────────────────────────────────
        // SNN (max 3)
        // ────────────────────────────────────────────────────────────────
        FullPreset {
            id: "snn-rate".to_string(),
            name: "Rate-Coded LIF".to_string(),
            description: "Rate encoder → LIF neurons".to_string(),
            family: "snn".to_string(),
            tags: vec!["snn".into(), "lif".into(), "rate".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, T, F]"}),
                ),
                node(
                    "enc",
                    "rate_encoder",
                    "Rate Encoder",
                    220,
                    140,
                    serde_json::json!({"encoding": "rate", "timesteps": 100}),
                ),
                node(
                    "lif",
                    "lif_neuron",
                    "LIF Neuron",
                    420,
                    140,
                    serde_json::json!({"tau": 10.0, "threshold": 1.0, "reset": 0.0, "decay": 0.9}),
                ),
                node(
                    "proj",
                    "linear_projection",
                    "Projection",
                    620,
                    140,
                    serde_json::json!({"in_features": 256, "out_features": 10, "bias": true}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    820,
                    140,
                    serde_json::json!({"shape": "[B, output_dim]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "enc"),
                conn("c2", "enc", "lif"),
                conn("c3", "lif", "proj"),
                conn("c4", "proj", "out"),
            ],
        },
        FullPreset {
            id: "snn-synaptic".to_string(),
            name: "Synaptic SNN".to_string(),
            description: "Synaptic layer with LIF + Leaky neurons".to_string(),
            family: "snn".to_string(),
            tags: vec!["snn".into(), "synaptic".into(), "bio".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, T, F]"}),
                ),
                node(
                    "syn",
                    "synaptic_layer",
                    "Synaptic Layer",
                    220,
                    140,
                    serde_json::json!({"in_features": 256, "out_features": 256, "delay": 1}),
                ),
                node(
                    "lif",
                    "lif_neuron",
                    "LIF Neuron",
                    420,
                    140,
                    serde_json::json!({"tau": 10.0, "threshold": 1.0, "reset": 0.0, "decay": 0.9}),
                ),
                node(
                    "leaky",
                    "leaky_neuron",
                    "Leaky Neuron",
                    620,
                    140,
                    serde_json::json!({"tau": 5.0, "threshold": 0.9, "reset": 0.0}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    820,
                    140,
                    serde_json::json!({"shape": "[B, output_dim]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "syn"),
                conn("c2", "syn", "lif"),
                conn("c3", "lif", "leaky"),
                conn("c4", "leaky", "out"),
            ],
        },
        FullPreset {
            id: "snn-stdp".to_string(),
            name: "STDP SNN".to_string(),
            description: "Spike-Timing-Dependent Plasticity network with LIF neurons".to_string(),
            family: "snn".to_string(),
            tags: vec![
                "snn".into(),
                "stdp".into(),
                "bio-inspired".into(),
                "unsupervised".into(),
            ],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, T, F]"}),
                ),
                node(
                    "enc",
                    "rate_encoder",
                    "Rate Encoder",
                    220,
                    140,
                    serde_json::json!({"encoding": "rate", "timesteps": 50}),
                ),
                node(
                    "syn",
                    "stdp_synapse",
                    "STDP Synapse",
                    420,
                    140,
                    serde_json::json!({"in_features": 784, "out_features": 400, "a_plus": 0.01, "a_minus": 0.0105, "tau_plus": 20.0, "tau_minus": 20.0}),
                ),
                node(
                    "lif1",
                    "lif_neuron",
                    "LIF Layer 1",
                    620,
                    140,
                    serde_json::json!({"tau": 10.0, "threshold": 1.0, "reset": 0.0, "decay": 0.9}),
                ),
                node(
                    "lif2",
                    "lif_neuron",
                    "LIF Layer 2",
                    820,
                    140,
                    serde_json::json!({"tau": 5.0, "threshold": 0.8, "reset": 0.0, "decay": 0.95}),
                ),
                node(
                    "proj",
                    "linear_projection",
                    "Readout",
                    1020,
                    140,
                    serde_json::json!({"in_features": 400, "out_features": 10, "bias": true}),
                ),
                node(
                    "out",
                    "output",
                    "Output",
                    1220,
                    140,
                    serde_json::json!({"shape": "[B, output_dim]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "enc"),
                conn("c2", "enc", "syn"),
                conn("c3", "syn", "lif1"),
                conn("c4", "lif1", "lif2"),
                conn("c5", "lif2", "proj"),
                conn("c6", "proj", "out"),
            ],
        },
        // ────────────────────────────────────────────────────────────────
        // RL (max 3)
        // ────────────────────────────────────────────────────────────────
        FullPreset {
            id: "rl-actor".to_string(),
            name: "Actor Head".to_string(),
            description: "Policy network head".to_string(),
            family: "rl".to_string(),
            tags: vec!["rl".into(), "policy".into(), "actor".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "State Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, state_dim]"}),
                ),
                node(
                    "proj",
                    "linear_projection",
                    "Backbone",
                    220,
                    140,
                    serde_json::json!({"in_features": 256, "out_features": 256, "bias": true, "activation": "relu"}),
                ),
                node(
                    "head",
                    "policy_head",
                    "Policy Head",
                    420,
                    140,
                    serde_json::json!({"d_model": 256, "action_dim": 12, "distribution": "categorical"}),
                ),
                node(
                    "out",
                    "output",
                    "Actions",
                    620,
                    140,
                    serde_json::json!({"shape": "[B, action_dim]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "proj"),
                conn("c2", "proj", "head"),
                conn("c3", "head", "out"),
            ],
        },
        FullPreset {
            id: "rl-critic".to_string(),
            name: "Value Head".to_string(),
            description: "Value network head".to_string(),
            family: "rl".to_string(),
            tags: vec!["rl".into(), "value".into(), "critic".into()],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "State Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, state_dim]"}),
                ),
                node(
                    "proj",
                    "linear_projection",
                    "Backbone",
                    220,
                    140,
                    serde_json::json!({"in_features": 256, "out_features": 256, "bias": true, "activation": "relu"}),
                ),
                node(
                    "head",
                    "value_head",
                    "Value Head",
                    420,
                    140,
                    serde_json::json!({"d_model": 256, "hidden_dim": 256}),
                ),
                node(
                    "out",
                    "output",
                    "Value",
                    620,
                    140,
                    serde_json::json!({"shape": "[B, 1]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "proj"),
                conn("c2", "proj", "head"),
                conn("c3", "head", "out"),
            ],
        },
        FullPreset {
            id: "dueling-dqn".to_string(),
            name: "Dueling DQN".to_string(),
            description: "Shared backbone → separate value + advantage streams → Q-values"
                .to_string(),
            family: "rl".to_string(),
            tags: vec![
                "rl".into(),
                "dqn".into(),
                "dueling".into(),
                "value-advantage".into(),
            ],
            nodes: vec![
                node(
                    "in",
                    "input",
                    "State Input",
                    50,
                    140,
                    serde_json::json!({"shape": "[B, state_dim]"}),
                ),
                node(
                    "shared",
                    "linear_projection",
                    "Shared Backbone",
                    220,
                    140,
                    serde_json::json!({"in_features": 256, "out_features": 512, "bias": true, "activation": "relu"}),
                ),
                node(
                    "val",
                    "value_head",
                    "Value Stream",
                    420,
                    140,
                    serde_json::json!({"d_model": 512, "hidden_dim": 256}),
                ),
                node(
                    "adv",
                    "advantage_stream",
                    "Advantage Stream",
                    420,
                    340,
                    serde_json::json!({"d_model": 512, "action_dim": 18, "hidden_dim": 256}),
                ),
                node(
                    "q",
                    "linear_projection",
                    "Q-Values (V + A)",
                    620,
                    140,
                    serde_json::json!({"in_features": 1, "out_features": 18, "bias": false, "activation": "none"}),
                ),
                node(
                    "out",
                    "output",
                    "Q-Values",
                    820,
                    140,
                    serde_json::json!({"shape": "[B, action_dim]"}),
                ),
            ],
            connections: vec![
                conn("c1", "in", "shared"),
                conn("c2", "shared", "val"),
                conn("c3", "shared", "adv"),
                conn("c4", "val", "q"),
                conn("c5", "adv", "q"),
                conn("c6", "q", "out"),
            ],
        },
    ]
}
