/**
 * Assembles the exportable project folder: the generated model code, the
 * hyperparameters already fixed in the app, a README built from the
 * analysis already on screen, and a training skeleton — bundled as a `.zip`
 * for local download, or as a file list the existing GitHub export panel can
 * push (same `{path, content}` shape it already uses).
 *
 * Regeneration is not a separate feature: every function here is a pure
 * function of the current canvas + hyperparameters + analysis. Re-run it
 * after any change and the output reflects the new state automatically —
 * there is nothing cached to go stale.
 */
import JSZip from 'jszip';
import { CanvasNode, Connection, AnalysisResult } from '@/types/architecture.ts';
import { HardwareConfig, ArchitectureFamily } from '@/contexts/HardwareContext.tsx';
import { ExportGitHubFile } from '@/services/neuraxApi.ts';
import { saveBinaryFile } from '@/services/desktopRuntime.ts';
import {
  generateModelCodeVerified,
  verifyCodegenAgainstAnalysis,
  ModelCodegenResult,
} from './modelCodeGen.ts';

export interface ProjectExportResult {
  files: ExportGitHubFile[];
  codegen: ModelCodegenResult;
  verification: ReturnType<typeof verifyCodegenAgainstAnalysis>;
  /** How many generation attempts the compile-until-verified loop needed.
   * Always 1 for today's deterministic generator — see the doc comment on
   * `compileUntilVerified` in `modelCodeGen.ts` for why that is expected,
   * not a sign the loop is unused. */
  attempts: number;
  slug: string;
}

function slugify(name: string): string {
  return name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'neurax_model';
}

function fmtInt(n: number | undefined): string {
  return typeof n === 'number' && Number.isFinite(n) ? n.toLocaleString('en-US') : 'n/a';
}

/**
 * NEURAX's signature across every generated file — one consistent mark,
 * not scattered mentions of different weight. The same principle as the
 * badges on NEURAX's own README: a claim that means something (verified /
 * not yet verified) rather than plain decoration, so it stays honest even
 * as it travels into someone else's repository.
 */
function signatureLine(verified: boolean): string {
  return verified
    ? 'Generated by NEURAX · code cross-checked against its own analysis, not just written to look right.'
    : 'Generated by NEURAX · contains layers outside NEURAX\'s verified set — see README before training.';
}

const NEURAX_URL = 'https://github.com/rustnew/NEURAX';

/** Same signature, as a `#`-commented block for a Python file header. */
function pySignatureHeader(verified: boolean): string {
  return [
    '# ──────────────────────────────────────────────────────────────',
    `# ${signatureLine(verified)}`,
    `# ${NEURAX_URL}`,
    '# ──────────────────────────────────────────────────────────────',
  ].join('\n');
}

function buildReadme(
  modelName: string,
  codegen: ModelCodegenResult,
  analysis: AnalysisResult | null,
  verification: ReturnType<typeof verifyCodegenAgainstAnalysis>,
  hw: HardwareConfig,
  /** True when the assistant wrote `model.py` rather than the translator.
   *  Said plainly: someone reading this folder in six months should not have
   *  to guess where the code came from. */
  authoredByAssistant = false,
): string {
  const verifiedBadge = codegen.fullySupported && verification.matches
    ? '![Generated by NEURAX](https://img.shields.io/badge/generated%20by-NEURAX-d79921?style=flat-square)&nbsp;![Verified](https://img.shields.io/badge/parameters-verified-2f9e44?style=flat-square)'
    : '![Generated by NEURAX](https://img.shields.io/badge/generated%20by-NEURAX-d79921?style=flat-square)&nbsp;![Needs review](https://img.shields.io/badge/parameters-needs%20review-e8590c?style=flat-square)';

  const lines: string[] = [
    `# ${modelName}`,
    '',
    verifiedBadge,
    '',
    `Generated by [NEURAX](${NEURAX_URL}) from the architecture compiled on the canvas`,
    '— this is a real, runnable project, not a description of one.',
    '',
    '## Status',
    '',
  ];

  if (authoredByAssistant) {
    lines.push(
      "`model.py` was written by NEURAX's assistant, not by its layer-by-layer translator —",
      'which is how a design the translator cannot express gets a runnable file at all.',
      '',
      'It was not taken on trust. Before it was accepted, PyTorch built it, the parameter',
      'count it really has was compared with the analysis below, and one batch of the',
      "declared input was pushed through it. Code that failed any of those was refused",
      'and never reached this folder.',
    );
  } else if (codegen.fullySupported) {
    lines.push(
      `All ${codegen.layers.length} layers were translated by NEURAX's verified code generator`,
      '(transformer / MoE / SSM / CNN-ResNet formula set — the same one behind the numbers',
      'already shown in the app).',
    );
  } else {
    lines.push(
      `${codegen.layers.length} layers total, **${codegen.unsupportedTypes.length} type(s) not yet`,
      'translated**: `' + codegen.unsupportedTypes.join('`, `') + '`.',
      '',
      'Those layers raise `NotImplementedError` in `model.py` rather than silently doing',
      'nothing — fill them in by hand, or simplify the design to NEURAX\'s verified',
      'families and re-export.',
    );
  }

  lines.push(
    '',
    '## Parameter count',
    '',
    authoredByAssistant
      ? `- PyTorch actually built: **${fmtInt(codegen.totalParams)}** parameters`
      : `- Generated code implies: **${fmtInt(codegen.totalParams)}** parameters`,
    `- NEURAX's analysis reports: **${fmtInt(analysis?.totalParams)}** parameters`,
    verification.matches
      ? `- These agree (within ${(verification.deltaPct * 100).toFixed(2)}%) — the code is a faithful reflection of the compiled design.`
      : `- **These disagree by ${(verification.deltaPct * 100).toFixed(1)}%** — expected while the design contains unsupported layers (they count toward the real total but contribute 0 to the generated code); if the design is fully supported and this still disagrees, do not train from this export.`,
    '',
  );

  if (analysis) {
    lines.push(
      '## Analysis, at export time',
      '',
      '| Metric | Value |',
      '|---|---|',
      `| Peak VRAM | ${analysis.memoryUsage ?? 'n/a'} |`,
      `| Training cost | ${typeof analysis.trainingCostUsd === 'number' ? `$${analysis.trainingCostUsd.toFixed(2)}` : 'n/a'} |`,
      `| Training time | ${typeof analysis.trainingTimeHours === 'number' ? `${analysis.trainingTimeHours.toFixed(1)} h` : 'n/a'} |`,
      `| FLOPs | ${analysis.estimatedFlops ?? 'n/a'} |`,
      `| OOM risk | ${analysis.oomRisk ?? 'n/a'} |`,
      '',
      'These numbers came from NEURAX at the moment of export. Re-open the design in NEURAX',
      'and re-export after any change — they are not re-computed by anything in this folder.',
      '',
    );
  }

  lines.push(
    '## Layout',
    '',
    '```',
    `${slugify(modelName)}/`,
    '├── README.md            — this file',
    '├── requirements.txt     — dependencies for this architecture family',
    '├── hyperparameters.json — exactly what was set in NEURAX\'s hyperparameter panel',
    '├── train.py              — entry point: loads the model + hyperparameters, trains',
    '├── src/',
    '│   ├── __init__.py',
    '│   └── model.py         — the architecture: real nn.Module(s), a real forward pass',
    '└── data/                 — put your dataset here (empty — see train.py)',
    '```',
    '',
    '`src/` is a real Python package (`from src.model import ...`), not a single script —',
    'split out on purpose so the architecture stays importable on its own, separately from',
    'the training loop that consumes it.',
    '',
    '## Running it',
    '',
    '```bash',
    'pip install -r requirements.txt',
    'python -m src.model    # prints the parameter count, cross-checked against NEURAX',
    '# put your dataset under data/, wire it into the marked section of train.py, then:',
    'python train.py',
    '```',
    '',
    `- Hardware target: ${hw.hardware ?? 'unspecified'} · precision: ${hw.precision ?? 'unspecified'} · batch size: ${hw.batchSize ?? 'unspecified'}`,
    '',
    '---',
    '',
    `Architecture designed and this project generated with [NEURAX](${NEURAX_URL}) —`,
    'know what a model costs before you spend a GPU-hour finding out.',
    '',
  );

  return lines.join('\n');
}

function buildHyperparametersJson(hw: HardwareConfig): string {
  // `_generated_by` is prefixed so it reads as metadata, not a hyperparameter
  // — anything doing `hp.get("someRealField")` never sees it, but a human (or
  // a script) looking at this file in isolation still knows where it came
  // from, exactly like every other file in this project.
  return JSON.stringify({ _generated_by: `NEURAX (${NEURAX_URL})`, ...hw }, null, 2) + '\n';
}

const REQUIREMENTS_BY_FAMILY: Record<string, string[]> = {
  transformer: ['torch>=2.1', 'datasets>=2.14', 'tokenizers>=0.15', 'tqdm'],
  moe: ['torch>=2.1', 'datasets>=2.14', 'tokenizers>=0.15', 'tqdm'],
  ssm: ['torch>=2.1', 'datasets>=2.14', 'tokenizers>=0.15', 'tqdm', '# mamba-ssm>=2.0  # optional: real CUDA selective-scan kernel'],
  cnn: ['torch>=2.1', 'torchvision>=0.16', 'tqdm'],
  vit: ['torch>=2.1', 'torchvision>=0.16', 'tqdm'],
  default: ['torch>=2.1', 'tqdm'],
};

function buildRequirementsTxt(family: ArchitectureFamily | undefined): string {
  const deps = REQUIREMENTS_BY_FAMILY[family ?? 'default'] ?? REQUIREMENTS_BY_FAMILY.default;
  return `# Generated by NEURAX · ${NEURAX_URL}\n` + deps.join('\n') + '\n';
}

function buildTrainPy(
  family: ArchitectureFamily | undefined,
  hw: HardwareConfig,
  className: string,
  verified: boolean,
): string {
  const isVision = family === 'cnn' || family === 'vit';
  const datasetBlock = isVision
    ? `    # ── Plug in your dataset here ───────────────────────────────────────
    # Any torchvision.datasets.ImageFolder-compatible layout works:
    #   data/train/<class_name>/*.jpg
    from torchvision import datasets, transforms
    transform = transforms.Compose([
        transforms.Resize((${hw.imgHeight ?? 224}, ${hw.imgWidth ?? 224})),
        transforms.ToTensor(),
    ])
    train_set = datasets.ImageFolder("data/train", transform=transform)  # <-- your path`
    : `    # ── Plug in your dataset here ───────────────────────────────────────
    # Any HuggingFace \`datasets\` dataset, or a local jsonl/text file, works.
    from datasets import load_dataset
    raw = load_dataset("text", data_files={"train": "data/train.txt"})  # <-- your path
    tokenizer = None  # <-- load the tokenizer this model's vocab_size was built from
    train_set = raw["train"]  # tokenize before training — left to you deliberately:
                               # NEURAX knows the model's shape, not your tokenizer`;

  return `${pySignatureHeader(verified)}
"""
Training entry point for ${className}, generated by NEURAX.

Hyperparameters below come from hyperparameters.json — the same values set in
NEURAX's hyperparameter panel — not re-guessed here.
"""
import json
import torch
from torch.utils.data import DataLoader
from src.model import ${className}

with open("hyperparameters.json") as f:
    hp = json.load(f)


def main():
${datasetBlock}

    loader = DataLoader(train_set, batch_size=hp.get("batchSize", ${hw.batchSize ?? 1}), shuffle=True)

    device = hp.get("device") or ("cuda" if torch.cuda.is_available() else "cpu")
    model = ${className}().to(device)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=hp.get("learningRate", ${hw.learningRate ?? 1e-4}),
        weight_decay=hp.get("weightDecay", 0.0),
    )

    num_epochs = hp.get("numEpochs", ${hw.numEpochs ?? 1})
    for epoch in range(num_epochs):
        for batch in loader:
            optimizer.zero_grad()
            # This step is architecture-specific by nature — NEURAX generated a
            # correct model and a correct optimizer setup; the loss function is
            # yours to plug in once the dataset above is real.
            raise NotImplementedError(
                "Wire up a forward pass + loss for your task here, then remove this line."
            )
        print(f"epoch {epoch + 1}/{num_epochs} done")


if __name__ == "__main__":
    main()
`;
}

/**
 * Model code that did not come from the translator, already verified.
 *
 * The assistant can write architectures NEURAX's own generator refuses to
 * express. When one has been built by PyTorch and matched against the
 * analysis, the exported project must contain *that* file — exporting the
 * translator's output instead would hand the user a folder that trains a
 * different model from the one their studio is running.
 */
export interface VerifiedModelOverride {
  code: string;
  modelClassName: string;
  /** What PyTorch actually built, not what anything predicted. */
  builtParams: number;
}

export function buildProjectFiles(
  nodes: CanvasNode[],
  connections: Connection[],
  hw: HardwareConfig,
  family: ArchitectureFamily | undefined,
  modelName: string,
  analysis: AnalysisResult | null,
  directory = '',
  override: VerifiedModelOverride | null = null,
): ProjectExportResult {
  const loop = generateModelCodeVerified(nodes, connections, hw, modelName, analysis?.totalParams ?? 0);
  const { verification: generatorVerification, attempts } = loop;
  // The override reached here by being built for real and compared with the
  // analysis, so it arrives already verified — `fullySupported` is true
  // because the question the flag answers ("can NEURAX express this?") is
  // moot for a file NEURAX did not have to express.
  const codegen: ModelCodegenResult = override
    ? {
        ...loop.result,
        code: override.code,
        modelClassName: override.modelClassName,
        totalParams: override.builtParams,
        fullySupported: true,
        unsupportedTypes: [],
      }
    : loop.result;
  const verification = override
    ? verifyCodegenAgainstAnalysis({ totalParams: override.builtParams }, analysis?.totalParams ?? 0)
    : generatorVerification;
  const slug = slugify(modelName);
  const dir = directory ? directory.replace(/\/+$/, '') + '/' : '';
  const verified = codegen.fullySupported && verification.matches;

  // A real package, not a pile of scripts: `src/` holds the architecture on
  // its own — importable, testable, independent of the training loop that
  // happens to consume it — the same separation NEURAX's own codebase keeps
  // between its compiler crates and the CLI/UI that drive them.
  const files: ExportGitHubFile[] = [
    { path: `${dir}src/__init__.py`, content: `# ${signatureLine(verified)}\n` },
    { path: `${dir}src/model.py`, content: `${pySignatureHeader(verified)}\n${codegen.code}` },
    { path: `${dir}hyperparameters.json`, content: buildHyperparametersJson(hw) },
    { path: `${dir}train.py`, content: buildTrainPy(family, hw, codegen.modelClassName, verified) },
    { path: `${dir}requirements.txt`, content: buildRequirementsTxt(family) },
    { path: `${dir}README.md`, content: buildReadme(modelName, codegen, analysis, verification, hw, override !== null) },
    {
      path: `${dir}data/.gitkeep`,
      content: `# Generated by NEURAX · ${NEURAX_URL}\n# Put your dataset here. See the marked section in train.py for how it is loaded.\n`,
    },
  ];

  return { files, codegen, verification, attempts, slug };
}

/** Zips the project and hands it to the platform's download/save flow — a
 * native "Save As" dialog on desktop, a browser download in the web build. */
export async function downloadProjectZip(result: ProjectExportResult): Promise<{ saved: boolean; path?: string }> {
  const zip = new JSZip();
  for (const file of result.files) {
    zip.file(file.path, file.content);
  }
  const bytes = await zip.generateAsync({ type: 'uint8array' });
  return saveBinaryFile(bytes, `${result.slug}.zip`, 'application/zip');
}
