/**
 * The property that matters most is not which words are coloured — it is that
 * nothing is lost. The highlighted layer sits underneath a transparent
 * textarea, so a tokenizer that drops or reorders one character misaligns the
 * caret from that point to the end of the file, and the editor stops being
 * usable rather than merely looking wrong.
 */
import { describe, it, expect } from 'vitest';
import { tokenizePython, TOKEN_CLASS, type TokenKind } from './pythonHighlight.ts';

const rebuild = (source: string) => tokenizePython(source).map((t) => t.text).join('');
const kindsOf = (source: string, text: string): TokenKind[] =>
  tokenizePython(source).filter((t) => t.text === text).map((t) => t.kind);

describe('tokenizePython — nothing is lost', () => {
  const samples = [
    'import torch.nn as nn\n',
    'class Net(nn.Module):\n    def __init__(self):\n        super().__init__()\n',
    '# a comment with "quotes" and a # inside\n',
    'x = f"{a!r} and {b:.2f}"\n',
    '"""triple\nquoted\nacross lines"""\n',
    "s = 'it\\'s escaped'\n",
    'lr = 3e-4\nn = 0x1F\nbig = 1_000_000\nhalf = .5\n',
    '@torch.no_grad()\ndef f(): pass\n',
    'a = 1-2\nb = 1 - 2\n',
    '',
    '\n\n\n',
    'unterminated = "oops\nnext_line = 1\n',
  ];

  for (const sample of samples) {
    it(`rebuilds exactly: ${JSON.stringify(sample.slice(0, 34))}`, () => {
      expect(rebuild(sample)).toBe(sample);
    });
  }

  it('rebuilds a whole generated-looking file', () => {
    const file = [
      '# Generated by NEURAX',
      'import torch',
      'import torch.nn as nn',
      '',
      '',
      'class NeuraxModel(nn.Module):',
      '    """A model.',
      '',
      '    With a docstring containing # and \'quotes\'.',
      '    """',
      '',
      '    def __init__(self, hidden: int = 768):',
      '        super().__init__()',
      '        self.fc = nn.Linear(hidden, 10, bias=False)',
      '        self.drop = nn.Dropout(0.1)',
      '',
      '    @torch.no_grad()',
      '    def forward(self, x):',
      '        return self.fc(self.drop(x))  # trailing comment',
      '',
    ].join('\n');
    expect(rebuild(file)).toBe(file);
  });
});

describe('tokenizePython — what gets coloured', () => {
  it('colours keywords, and does not colour self as one', () => {
    expect(kindsOf('class Net:', 'class')).toEqual(['keyword']);
    // `self` is a convention, not a keyword. Colouring it as one is wrong,
    // and it is the mistake every hand-written Python highlighter makes.
    expect(kindsOf('def f(self):', 'self')).toEqual(['builtin']);
  });

  it('names the class and function being defined', () => {
    expect(kindsOf('class NeuraxModel(nn.Module):', 'NeuraxModel')).toEqual(['definition']);
    expect(kindsOf('    def forward(self, x):', 'forward')).toEqual(['definition']);
    // But not a call of the same name elsewhere.
    expect(kindsOf('y = forward(x)', 'forward')).toEqual([]);
  });

  it('does not read a keyword inside a string as a keyword', () => {
    const tokens = tokenizePython('s = "class def return"');
    expect(tokens.some((t) => t.kind === 'keyword')).toBe(false);
  });

  it('does not read a # inside a string as a comment', () => {
    const tokens = tokenizePython('s = "a # b"\nreturn s');
    expect(tokens.some((t) => t.kind === 'comment')).toBe(false);
    expect(kindsOf('s = "a # b"\nreturn s', 'return')).toEqual(['keyword']);
  });

  it('does not read a quote inside a comment as a string', () => {
    const tokens = tokenizePython('# it\'s fine\nx = 1');
    expect(tokens.filter((t) => t.kind === 'string')).toEqual([]);
  });

  it('keeps an unterminated quote on its own line', () => {
    // One stray quote must not colour the rest of the file as a string.
    const tokens = tokenizePython('a = "oops\nreturn 1');
    expect(kindsOf('a = "oops\nreturn 1', 'return')).toEqual(['keyword']);
    expect(tokens.find((t) => t.kind === 'string')?.text).toBe('"oops');
  });

  it('reads f-strings and raw strings as strings, prefix included', () => {
    expect(tokenizePython('x = f"{a}"').find((t) => t.kind === 'string')?.text).toBe('f"{a}"');
    expect(tokenizePython('p = r"\\d+"').find((t) => t.kind === 'string')?.text).toBe('r"\\d+"');
  });

  it('reads a triple-quoted docstring as one string across lines', () => {
    const source = '"""line one\nline two"""';
    expect(tokenizePython(source)).toEqual([{ kind: 'string', text: source }]);
  });

  it('reads exponents but stops a number at a minus that is an operator', () => {
    expect(tokenizePython('lr = 3e-4').find((t) => t.kind === 'number')?.text).toBe('3e-4');
    const subtraction = tokenizePython('n = 1-2').filter((t) => t.kind === 'number');
    expect(subtraction.map((t) => t.text)).toEqual(['1', '2']);
  });

  it('reads a decorator with its dotted path', () => {
    expect(tokenizePython('@torch.no_grad()').find((t) => t.kind === 'decorator')?.text)
      .toBe('@torch.no_grad');
  });
});

describe('TOKEN_CLASS', () => {
  it('gives every kind a class, so no token renders unstyled', () => {
    const kinds: TokenKind[] = [
      'plain', 'keyword', 'builtin', 'string', 'number', 'comment', 'decorator', 'definition',
    ];
    for (const kind of kinds) {
      expect(TOKEN_CLASS[kind], kind).toBeTruthy();
    }
  });

  it('takes every colour from a theme token, never a fixed hex', () => {
    // A literal colour here would be right in one of the four themes and
    // wrong in the other three — the exact defect the palette exists to stop.
    for (const [kind, className] of Object.entries(TOKEN_CLASS)) {
      expect(className, kind).not.toMatch(/#[0-9a-fA-F]{3,8}/);
      expect(className, kind).not.toMatch(/\b(?:rgb|rgba)\(/);
    }
  });
});
