//! Real-world data for comparison with computed metrics

pub struct RealWorldData {
    pub model_name: String,
    pub total_params: u64,
    pub training_tokens: u64,
    pub training_cost_usd: f64,
    pub training_time_hours: f64,
    pub peak_memory_gb: f64,
    pub inference_latency_ms: f64,
    pub throughput_tokens_per_s: f64,
    pub gpu_count: u32,
    pub gpu_type: String,
    pub source: String,
}

impl RealWorldData {
    pub fn for_model(name: &str) -> Self {
        match name {
            "GPT-3 175B" => Self {
                model_name: "GPT-3 175B".to_string(),
                total_params: 175_000_000_000,
                training_tokens: 300_000_000_000,
                training_cost_usd: 4_600_000.0,
                training_time_hours: 34.0 * 24.0, // ~34 days
                peak_memory_gb: 350.0,
                inference_latency_ms: 250.0,
                throughput_tokens_per_s: 100.0,
                gpu_count: 10_000,
                gpu_type: "V100".to_string(),
                source: "OpenAI 2020, Brown et al.".to_string(),
            },
            "LLaMA-2 70B" => Self {
                model_name: "LLaMA-2 70B".to_string(),
                total_params: 70_000_000_000,
                training_tokens: 2_000_000_000_000,
                training_cost_usd: 2_000_000.0,
                training_time_hours: 48.0 * 24.0,
                peak_memory_gb: 140.0,
                inference_latency_ms: 35.0,
                throughput_tokens_per_s: 2800.0,
                gpu_count: 2048,
                gpu_type: "A100".to_string(),
                source: "Meta 2023, Touvron et al.".to_string(),
            },
            "Mixtral 8x7B" => Self {
                model_name: "Mixtral 8x7B".to_string(),
                total_params: 47_000_000_000,
                training_tokens: 500_000_000_000,
                training_cost_usd: 500_000.0,
                training_time_hours: 7.0 * 24.0,
                peak_memory_gb: 90.0,
                inference_latency_ms: 15.0,
                throughput_tokens_per_s: 4500.0,
                gpu_count: 256,
                gpu_type: "A100".to_string(),
                source: "Mistral AI 2023".to_string(),
            },
            "DeepSeek-V3" => Self {
                model_name: "DeepSeek-V3".to_string(),
                total_params: 671_000_000_000,
                training_tokens: 14_800_000_000_000,
                training_cost_usd: 5_576_000.0,
                training_time_hours: 55.0 * 24.0,
                peak_memory_gb: 800.0,
                inference_latency_ms: 80.0,
                throughput_tokens_per_s: 1500.0,
                gpu_count: 2048,
                gpu_type: "H100".to_string(),
                source: "DeepSeek 2024".to_string(),
            },
            "Mamba 2.8B" => Self {
                model_name: "Mamba 2.8B".to_string(),
                total_params: 2_800_000_000,
                training_tokens: 300_000_000_000,
                training_cost_usd: 50_000.0,
                training_time_hours: 48.0,
                peak_memory_gb: 12.0,
                inference_latency_ms: 5.0,
                throughput_tokens_per_s: 8000.0,
                gpu_count: 8,
                gpu_type: "A100".to_string(),
                source: "Gu & Dao 2023".to_string(),
            },
            "RWKV 7B" => Self {
                model_name: "RWKV 7B".to_string(),
                total_params: 7_000_000_000,
                training_tokens: 330_000_000_000,
                training_cost_usd: 100_000.0,
                training_time_hours: 72.0,
                peak_memory_gb: 28.0,
                inference_latency_ms: 12.0,
                throughput_tokens_per_s: 5000.0,
                gpu_count: 32,
                gpu_type: "A100".to_string(),
                source: "RWKV Team 2023".to_string(),
            },
            "ResNet-50" => Self {
                model_name: "ResNet-50".to_string(),
                total_params: 25_600_000,
                training_tokens: 0,
                training_cost_usd: 500.0,
                training_time_hours: 8.0,
                peak_memory_gb: 8.0,
                inference_latency_ms: 2.0,
                throughput_tokens_per_s: 1000.0,
                gpu_count: 8,
                gpu_type: "V100".to_string(),
                source: "He et al. 2015".to_string(),
            },
            "VGG-16" => Self {
                model_name: "VGG-16".to_string(),
                total_params: 138_000_000,
                training_tokens: 0,
                training_cost_usd: 300.0,
                training_time_hours: 4.0,
                peak_memory_gb: 16.0,
                inference_latency_ms: 3.0,
                throughput_tokens_per_s: 800.0,
                gpu_count: 4,
                gpu_type: "V100".to_string(),
                source: "Simonyan & Zisserman 2014".to_string(),
            },
            "Stable Diffusion 1.5" => Self {
                model_name: "Stable Diffusion 1.5".to_string(),
                total_params: 983_000_000,
                training_tokens: 0,
                training_cost_usd: 600_000.0,
                training_time_hours: 150_000.0, // GPU-hours
                peak_memory_gb: 10.0,
                inference_latency_ms: 2000.0,
                throughput_tokens_per_s: 0.5,
                gpu_count: 256,
                gpu_type: "A100".to_string(),
                source: "Stability AI 2022".to_string(),
            },
            "SDXL 1.0" => Self {
                model_name: "SDXL 1.0".to_string(),
                total_params: 2_600_000_000,
                training_tokens: 0,
                training_cost_usd: 2_000_000.0,
                training_time_hours: 300_000.0,
                peak_memory_gb: 20.0,
                inference_latency_ms: 5000.0,
                throughput_tokens_per_s: 0.2,
                gpu_count: 512,
                gpu_type: "A100".to_string(),
                source: "Stability AI 2023".to_string(),
            },
            _ => Self::default_for(name),
        }
    }
    
    fn default_for(name: &str) -> Self {
        Self {
            model_name: name.to_string(),
            total_params: 0,
            training_tokens: 0,
            training_cost_usd: 0.0,
            training_time_hours: 0.0,
            peak_memory_gb: 0.0,
            inference_latency_ms: 0.0,
            throughput_tokens_per_s: 0.0,
            gpu_count: 0,
            gpu_type: "Unknown".to_string(),
            source: "No data available".to_string(),
        }
    }
}
